version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - db
    
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: studyrooms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
